# Generated by Django 5.1.6 on 2025-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='course',
            field=models.ManyToManyField(related_name='courses', to='app_conf.course'),
        ),
    ]
