# Generated by Django 5.1.6 on 2025-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0002_alter_studentmodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='course',
            field=models.ManyToManyField(related_name='students_course', to='app_conf.course'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='group',
            field=models.ManyToManyField(related_name='students_group', to='app_conf.group'),
        ),
    ]
