# Generated by Django 5.1.6 on 2025-03-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0003_alter_studentmodel_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='group',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_conf.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students_group', to='app_conf.group'),
            preserve_default=False,
        ),
    ]
