# Generated by Django 5.1.6 on 2025-03-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0004_remove_studentmodel_course_remove_studentmodel_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='group_students', to='app_conf.studentmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='app_conf.group'),
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.studentmodel')),
            ],
        ),
    ]
