# Generated by Django 5.1.6 on 2025-03-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0005_alter_group_students_alter_studentmodel_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
