# Generated by Django 5.1.6 on 2025-03-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0006_studentmodel_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherworkermodel',
            name='user',
        ),
    ]
